homepage:
  path: /
  defaults: { _controller: AppBundle:Default:index }
  methods:  [GET]

# warehouse
warehouseList:
  path: /warehouse
  defaults: { _controller: AppBundle:Warehouse:list }
  methods:  [GET]

warehouseNew:
  path: /warehouse/new
  defaults: { _controller: AppBundle:Warehouse:new }
  methods:  [GET, POST]

# Products
productList:
  path: /product
  defaults: { _controller: AppBundle:Product:list }
  methods:  [GET]

productNew:
  path: /product/new
  defaults: { _controller: AppBundle:Product:new }
  methods:  [GET, POST]

# Contractor
contractorList:
  path: /contractor
  defaults: { _controller: AppBundle:Contractor:list }
  methods:  [GET]

contractorNew:
  path: /contractor/new
  defaults: { _controller: AppBundle:Contractor:new }
  methods:  [GET, POST]

# Incomes
incomeList:
  path: /income
  defaults: { _controller: AppBundle:Income:list }
  methods:  [GET]

incomeNew:
  path: /income/new
  defaults: { _controller: AppBundle:Income:new }
  methods:  [GET, POST]

incomeEdit:
  path: /income/{id}
  defaults: { _controller: AppBundle:Income:edit }
  methods:  [GET, POST]

outcomeList:
  path: /outcome
  defaults: { _controller: AppBundle:Operation:outcomeList }
  methods:  [GET]

outcomeNew:
  path: /outcome/new
  defaults: { _controller: AppBundle:Operation:outcomeNew }
  methods:  [GET, POST]

outcomeEdit:
  path: /outcome/{operationId}
  defaults: { _controller: AppBundle:Operation:outcomeEdit }
  methods:  [GET, POST]
