homepage:
  path: /
  defaults: { _controller: AppBundle:Default:index }
  methods:  [GET]

warehouseList:
  path: /warehouse
  defaults: { _controller: AppBundle:Warehouse:list }
  methods:  [GET]

warehouseNew:
  path: /warehouse/new
  defaults: { _controller: AppBundle:Warehouse:new }
  methods:  [GET, POST]

warehouseGet:
  path: /warehouse/{id}
  defaults: { _controller: AppBundle:Warehouse:get }
  methods:  [GET]

warehouseEdit:
  path: /warehouse/{id}
  defaults: { _controller: AppBundle:Warehouse:edit }
  methods:  [POST]