AppBundle\Entity\IncomeElement:
    type: entity
    table: income_element
    repositoryClass: AppBundle\Entity\Repository\IncomeElementRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        basePrice:
            type: decimal
            precision: 10
            scale: 2
            nullable: false
        quantity:
            type: decimal
            precision: 10
            scale: 2
            nullable: false
        value:
            type: decimal
            precision: 10
            scale: 2
            nullable: false
    manyToOne:
        income:
            targetEntity: Income
            inversedBy: elements
            joinColumn:
                name: income_id
                referencedColumnName: id
        product:
            targetEntity: Product
            fetch: EAGER
            joinColumn:
                name: product_id
                referencedColumnName: id