AppBundle\Entity\Product:
    type: entity
    table: product
    repositoryClass: AppBundle\Entity\Repository\ProductRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
            nullable: false
        unit:
            type: string
            length: 15
            nullable: false
